import type { TreeInfo } from '../base/tree/Tree'

export const appleTrees: TreeInfo[] = [
	// 左上角房子旁边的树
	{ x: 15, y: 11, state: 'common' },
	{ x: 14, y: 12, state: 'common' },
	{ x: 14, y: 15, state: 'common' },
	{ x: 16, y: 11, state: 'common' },
	{ x: 18, y: 11, state: 'common' },
	{ x: 22, y: 12, state: 'common' },
	{ x: 21, y: 13, state: 'bearFruit' },
	{ x: 23, y: 13, state: 'common' },
	// 中间山丘上的树
	{ x: 42, y: 13, state: 'bearFruit' },
	{ x: 45, y: 13, state: 'common' },
	{ x: 51, y: 13, state: 'common' },
	{ x: 41, y: 14, state: 'common' },
	{ x: 51, y: 14, state: 'common' },
	{ x: 41, y: 15, state: 'common' },
	// 中间山丘下的树
	{ x: 54, y: 19, state: 'bearFruit' },
	{ x: 56, y: 20, state: 'common' },
	{ x: 57, y: 21, state: 'common' },
	// 中间下方森林
	{ x: 32, y: 33, state: 'common' },
	{ x: 35, y: 33, state: 'common' },
	{ x: 34, y: 34, state: 'common' },
	{ x: 38, y: 34, state: 'common' },
	{ x: 34, y: 35, state: 'common' },
	{ x: 36, y: 35, state: 'common' },
	{ x: 38, y: 36, state: 'common' },
	{ x: 41, y: 36, state: 'common' },
	{ x: 39, y: 36, state: 'common' },
	{ x: 37, y: 37, state: 'common' },
	{ x: 40, y: 37, state: 'common' },
	{ x: 43, y: 37, state: 'common' },
	{ x: 45, y: 37, state: 'common' },
	{ x: 42, y: 38, state: 'common' },
	{ x: 44, y: 39, state: 'common' },
	{ x: 45, y: 39, state: 'common' },
	{ x: 47, y: 40, state: 'common' },
	// 左下角岛屿桥旁边的树
	{ x: 24, y: 27, state: 'common' },
	{ x: 25, y: 28, state: 'common' },
	{ x: 26, y: 34, state: 'common' },
	// 左下角的树
	{ x: 11, y: 35, state: 'common' },
	{ x: 9, y: 37, state: 'common' },
	{ x: 8, y: 39, state: 'common' },
	{ x: 8, y: 40, state: 'common' },
	{ x: 10, y: 41, state: 'common' },
	{ x: 9, y: 42, state: 'common' },
	// 左下角山丘上的树
	{ x: 15, y: 35, state: 'common' },
	{ x: 18, y: 35, state: 'common' },
	{ x: 17, y: 35, state: 'common' },
	{ x: 20, y: 35, state: 'common' },
	{ x: 18, y: 42, state: 'common' },
	{ x: 18, y: 43, state: 'common' },
	{ x: 23, y: 38, state: 'common' },
	{ x: 22, y: 38, state: 'common' },
	{ x: 23, y: 39, state: 'common' },
	{ x: 25, y: 41, state: 'common' },
	{ x: 26, y: 42, state: 'common' },
	{ x: 26, y: 43, state: 'common' }
]
